### ISSUE TITLE
Leverage `hubAI()` instead

### ISSUE THREAD

**Issue by atinux** [awecode/pdf-summarizer#1]
This would simplify the code and avoid using external env variables for Cloudflare 😊 

Beautiful work btw ❤️

**Comment by isDipesh** [comment]
Thanks. Updated to use `hubAI` now.

> This would simplify the code and avoid using external env variables for Cloudflare 😊

I had kept the env variables in case it needs to be deployed outside the Cloudflare environment and AI binding is not available.

> Beautiful work btw ❤️

Thanks. This is only possible because of your and the Nuxt team's vision and hard work. 💚

**Comment by atinux** [comment]
Feel free to add the `nuxthub` topic also so it can be listed on https://github.com/topics/nuxthub
